name: upload kaart.csv
#mijn eerste yaml-script

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '30 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://www.nrc.nl/feeds/wilde-tuin/kaart.csv > kaart.csv
    - task: PythonScript@0
      inputs:
        scriptSource: 'inline' # Options: filePath, inline
        #scriptPath: /.github/workflows/filter_kaartdata.py # Required when scriptSource == filePath
        script: |-
          import matplotlib.pyplot as plt
          import pandas as pd
          import numpy as np
          url1 = 'https://www.nrc.nl/feeds/wilde-tuin/kaart.csv'
          df = pd.read_csv(url1)
          df.loc[(df['soortgroep'] != 'Planten') & (df['soortgroep'] != 'Vogels')]
          df = df[['datum','soort','soortgroep','foto']]
          df.to_csv(r'beestjesselectie.csv', index = True)# Required when scriptSource == inline
        #arguments: # Optional
        #pythonInterpreter: # Optional
        #workingDirectory: # Optional
        #failOnStderr: false # Optional

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
