name: upload kaart.csv
#mijn eerste yaml-script

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '30 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://www.nrc.nl/feeds/wilde-tuin/kaart.csv > kaart.csv
    - name: Install pandas
      run: conda install pandas
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: pythonscript uitvoeren
      shell: python
      run: |
        python -c
        "import pandas as pd"
        "url1='https://www.nrc.nl/feeds/wilde-tuin/kaart.csv'"
        "df=pd.read_csv(url1)"
        "df.loc[(df['soortgroep']!='Planten') & (df['soortgroep']!='Vogels')]"
        "df=df[['datum','soort','soortgroep','foto']]"
        "print(df.head(10))"
        "df.to_csv(r'beestjesselectie.csv',index=True)"
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
